install ack
install bash
install cmake
install coreutils
install ctags
install findutils
install fish
install freetype
install gdbm
install git
install gitsh
install gnu-sed
install grep
install libidn
install memcached
install multimarkdown
install node
install phantomjs
install postgresql
install rbenv
install redis
install ruby-build
install sqlite
install the_silver_searcher
install tree
install vim
install webkit2png
install wget
install znc
