#!/usr/bin/env ruby

# Open xcode without any previous projects being opened as well.
# We first look for a workspace, then a project in the current directory, opening the first that is found.

f = []
f.concat Dir["*.xcworkspace"]
f.concat Dir["*.xcodeproj"]

xcode_path = `xcode-select -p`
xcode_path = File.dirname(File.dirname(xcode_path))
if f.length > 0
  puts "opening #{f.first} with #{xcode_path}"
  `open -a #{xcode_path} #{f.first} --args -ApplePersistenceIgnoreState YES`
  exit_code = `echo $?`
  exit 0
end

puts "No Xcode projects found"
exit 1

# From http://stackoverflow.com/questions/19639914/how-to-run-xcode-from-command-line
