install ack
install bash
install coreutils
install ctags
install findutils
install fish
install freetype
install git
install gnu-sed
install heroku-toolbelt
install hub
install imagemagick
install libidn
install memcached
install mongodb
install multimarkdown
install mysql
install node
install phantomjs
install postgresql
install qt
install rbenv
install redis
install ruby-build
install sqlite
install the_silver_searcher
install tmux
install tree
install vim
install webkit2png
install wget
tap homebrew/dupes
install grep
tap thoughtbot/formulae
install gitsh
linkapps
services start mysql
services start redis
