#!/usr/bin/env ruby

# Git pre-commit hook that tells user to install some *real* git hooks.
#
# I have a great (IMO) git pre-commit hook, but I never remember to install it 
# into new projects.  I can't use the 
# 
# git config --global init.templatedir '~/.git_template'
#
# trick to install the GOOD pre-commit hooks, since I install symlinks
# to ensure that even old projects are always using up-to-date hooks.
# So, I set up this default hook to remind me (and others) to install the 
# GOOD hooks.  
# 
# I could, theoretically, install the good hooks by running code
# inside THIS hook, but that feels too creepy and invasive.
# So, I just show a reminder.

# Check to see if we have a records of a git repo already installed.
SYMLINK_SOURCE_REPO = `git config hooks.symlinksourcerepo`.strip
repo_exists = (!SYMLINK_SOURCE_REPO.strip.empty?) && (File.directory?(SYMLINK_SOURCE_REPO) || File.symlink?(SYMLINK_SOURCE_REPO))

if repo_exists
message = <<END

You've already installed git pre-commit hooks, at 
#{SYMLINK_SOURCE_REPO},
but this git repository isn't using them.

To use those git hooks,

cd #{SYMLINK_SOURCE_REPO}
./setup.sh #{File.dirname(File.dirname(File.dirname(File.expand_path(__FILE__))\
))}
cd #{File.dirname(File.dirname(File.dirname(File.expand_path(__FILE__))))} #cd \
back here

(More information is available at...
https://github.com/bobgilmore/githooks#installation )

If instead you just want this message to go away so that you can commit
normally, run...

rm #{File.expand_path(__FILE__)}

@bob_gilmore

END
else
message = <<END

This git repository isn't using a good git pre-commit hook - it's just using
this warning message one installed by https://github.com/bobgilmore/dotfiles

This is a bad idea - good hooks can save you a *lot* of trouble. I recommend 
installing some.  You can write your own, or start with the ones in my 
Github project. To install mine, run...

cd <some directory where you can clone a Git repo.  I use ~/code >
git clone git@github.com:bobgilmore/githooks.git #clone the repo
cd githooks
./setup.sh #{File.dirname(File.dirname(File.dirname(File.expand_path(__FILE__))))}
cd #{File.dirname(File.dirname(File.dirname(File.expand_path(__FILE__))))} #cd back here

(More information is available at...
https://github.com/bobgilmore/githooks#installation )

If instead you just want this message to go away so that you can commit 
normally, run...

rm #{File.expand_path(__FILE__)}

@bob_gilmore

END
end

puts message
exit 1
